networks:
  proxy:
    external: true

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 9001
    volumes:
      - /homelab/authelia/data/:/data
      - ./config/users.yml:/data/users.yml
      - ./config/configuration.yml:/config/configuration.yml
    env_file:
      - .env
    labels:
      # HTTPS
      - traefik.enable=true
      - traefik.http.routers.authelia-secure.tls=true
      - traefik.http.routers.authelia-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.authelia-secure.entrypoints=websecure
      - traefik.http.routers.authelia-secure.tls.certresolver=production
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9001/api/verify?rd=https://${HOSTNAME}
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-user,Remote-Groups,Remote-Name,Remote-Email