networks:
  proxy:
    external: true

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - /homelab/pihole/data:/etc/pihole
      - /homelab/pihole/dnsmasq.d:/etc/dnsmasq.d
    labels:
      # HTTP
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.pihole.entrypoints=web
      - traefik.http.routers.pihole.middlewares=pihole-https-redirect
      - traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.services.pihole.loadbalancer.server.port=80
      # HTTPS
      - traefik.http.routers.pihole-secure.tls=true
      - traefik.http.routers.pihole-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.pihole-secure.entrypoints=websecure
      - traefik.http.routers.pihole-secure.tls.certresolver=production