networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /homelab/traefik/data:/etc/traefik
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    labels:
      # HTTPS
      - traefik.enable=true
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.tls.certresolver=production
      - traefik.http.routers.traefik-secure.service=api@internal
      - traefik.http.routers.traefik-secure.middlewares=authelia@docker
