networks:
  proxy:
    external: true
  internal:

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - /homelab/nextcloud/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - internal

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - /homelab/nextcloud/data:/var/www/html
      - /home:/var/www/html/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - internal

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - /homelab/nextcloud/data:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - internal
      - proxy

  cron:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /homelab/nextcloud/data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - internal