host: 0.0.0.0
port: 9001
log_level: debug
theme: dark
jwt_secret: secret # Cambiar esto
default_redirection_url: https://auth.example.com # Cambiar esto
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users.yml
    # docker run authelia/authelia:latest authelia hash-password 'authelia'
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny

session:
  name: authelia_session
  secret: secret # Cambiar esto
  expiration: 3600 # 1 hora
  inactivity: 300 # 5 minutos
  domain: example.com # Cambiar esto

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt
