theme: dark
jwt_secret: 'secret' # Cambiar esto
default_redirection_url: 'https://auth.example.com' # Cambiar esto

server:
  host: 0.0.0.0
  port: 9001

log:
  level: debug

totp:
  issuer: 'authelia.com'

authentication_backend:
  file:
    path: /data/users.yml
    # docker run authelia/authelia:latest authelia hash-password 'authelia'
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: 'www.example.com'
      policy: bypass
    - domain: '*.example.com'
      policy: two_factor

session:
  name: authelia_session
  secret: 'secret' # Cambiar esto
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: 'example.com' # Cambiar esto

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: 'secret' # Cambiar esto
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
    username: myaccount@gmail.com # Cambiar esto
    password: yourapppassword # Cambiar esto
    sender: admin@example.com # Cambiar esto
    host: smtp.gmail.com
    port: 587

identity_providers:
  oidc:
    hmac_secret: this_is_a_secret_abc123abc123abc # Cambiar esto
    issuer_private_key: this_is_a_secret_abc123abc123abc # Cambiar esto
    clients:
      - id: portainer
        secret: this_is_a_secret_abc123abc123abc # Cambiar esto
        public: false
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://portainer.example.com
        userinfo_signing_algorithm: none
